# -*- coding: utf-8 -*-
"""cobatest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18686pZc_-LiMdCcpEhz5Gkf6omlf3WH1
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import requests
import gspread
from google.oauth2.service_account import Credentials

# ========== KONFIGURASI ==========
SUPABASE_URL = "https://zywsjxwavkpjjzgsipow.supabase.co"
ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5d3NqeHdhdmtwamp6Z3NpcG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1OTM1MTAsImV4cCI6MjA4ODE2OTUxMH0.Jfnr96WIuz2wBLWvVMraPnCH1f3cxllkjlTSCpB6Adw"

SPREADSHEET_ID = "1Ll0TD_xlCVCLxMuUCthcnn_fqsyxlLVe31GS8LBotvI"
CREDS_FILE = "rich-world-471802-j4-7ccc319e6683.json"

# Daftar tabel/view yang akan diekspor
TABLES = [
    {"name": "stg_sales", "sheet": "stg_sales"},
    {"name": "dim_product", "sheet": "dim_product"},
    {"name": "dim_customer", "sheet": "dim_customer"},
    {"name": "dim_sales", "sheet": "dim_sales"},
    {"name": "dim_date", "sheet": "dim_date"},
    {"name": "fact_sales", "sheet": "fact_sales"},
    {"name": "v_sales_summary", "sheet": "v_sales_summary"},
    {"name": "v_dash_monthly", "sheet": "v_dash_monthly"},
    {"name": "v_dash_product", "sheet": "v_dash_product"},
    {"name": "v_dash_city", "sheet": "v_dash_city"},
]

# ========== FUNGSI ==========
def fetch_supabase_table(table_name):
    """Ambil semua data dari tabel/view Supabase."""
    url = f"{SUPABASE_URL}/rest/v1/{table_name}?select=*"
    headers = {
        "apikey": ANON_KEY,
        "Authorization": f"Bearer {ANON_KEY}"
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Error {response.status_code}: {response.text}")

def write_to_google_sheets(data, sheet_name):
    """Tulis data ke sheet tertentu di spreadsheet."""
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds = Credentials.from_service_account_file(CREDS_FILE, scopes=scope)
    client = gspread.authorize(creds)
    sh = client.open_by_key(SPREADSHEET_ID)

    # Buat atau ambil worksheet
    try:
        worksheet = sh.worksheet(sheet_name)
        worksheet.clear()
    except:
        worksheet = sh.add_worksheet(title=sheet_name, rows=1000, cols=20)

    if not data:
        worksheet.append_row(["Tidak ada data"])
        return

    df = pd.DataFrame(data)
    worksheet.update([df.columns.values.tolist()] + df.values.tolist())

# ========== EKSEKUSI ==========
for tbl in TABLES:
    print(f"Memproses {tbl['name']}...")
    try:
        data = fetch_supabase_table(tbl["name"])
        write_to_google_sheets(data, tbl["sheet"])
        print(f"  -> {len(data)} baris ditulis ke sheet '{tbl['sheet']}'")
    except Exception as e:
        print(f"  -> Gagal: {e}")

import os
file_path = 'rich-world-471802-j4-7ccc319e6683.json'
if os.path.exists(file_path):
    print("File ditemukan.")
else:
    print("File tidak ditemukan di direktori:", os.getcwd())