# -*- coding: utf-8 -*-
"""upload_to_supabase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOHOZJadCCoZY7ThrdYE1v-dCCNhGGl6
"""

from google.colab import files
uploaded = files.upload()

pip install python-dotenv psycopg2

"""
Script untuk upload data CSV ke tabel stg_sales di Supabase.
Membaca file CSV, menambahkan UUID unik untuk setiap baris, lalu mengupload ke database.
"""

import pandas as pd
from sqlalchemy import create_engine
import uuid

#
DATABASE_URL = f"postgresql://postgres.zywsjxwavkpjjzgsipow:Astagfirullahaladzim%4012@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres"

#
CSV_FILE = "/content/sales.csv"

#
engine = create_engine(DATABASE_URL)

# Baca CSV
df = pd.read_csv(CSV_FILE)
print(f"File CSV dibaca: {len(df)} baris ditemukan.")

#
df['unique_key'] = [str(uuid.uuid4()) for _ in range(len(df))]

#
df.to_sql('stg_sales', engine, if_exists='append', index=False)

print(f"Sukses mengupload {len(df)} baris ke tabel stg_sales.")

"""Replace `<library_name>` with the actual name of the library you want to install. For example, to install the `requests` library, you would use `pip install requests`."""